// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: cmd/api/protos/tracker-api.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MoodType, the possible values for a mood.
type MoodState int32

const (
	MoodState_Happy MoodState = 0 // Happy feeling
	MoodState_Sad   MoodState = 1 // Sad feeling
)

// Enum value maps for MoodState.
var (
	MoodState_name = map[int32]string{
		0: "Happy",
		1: "Sad",
	}
	MoodState_value = map[string]int32{
		"Happy": 0,
		"Sad":   1,
	}
)

func (x MoodState) Enum() *MoodState {
	p := new(MoodState)
	*p = x
	return p
}

func (x MoodState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MoodState) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_api_protos_tracker_api_proto_enumTypes[0].Descriptor()
}

func (MoodState) Type() protoreflect.EnumType {
	return &file_cmd_api_protos_tracker_api_proto_enumTypes[0]
}

func (x MoodState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MoodState.Descriptor instead.
func (MoodState) EnumDescriptor() ([]byte, []int) {
	return file_cmd_api_protos_tracker_api_proto_rawDescGZIP(), []int{0}
}

// Mood definition.
type Mood struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State MoodState `protobuf:"varint,1,opt,name=State,proto3,enum=tracker.MoodState" json:"State,omitempty"` // MoodState defines the mood state among defined values.
}

func (x *Mood) Reset() {
	*x = Mood{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_api_protos_tracker_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mood) ProtoMessage() {}

func (x *Mood) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_api_protos_tracker_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mood.ProtoReflect.Descriptor instead.
func (*Mood) Descriptor() ([]byte, []int) {
	return file_cmd_api_protos_tracker_api_proto_rawDescGZIP(), []int{0}
}

func (x *Mood) GetState() MoodState {
	if x != nil {
		return x.State
	}
	return MoodState_Happy
}

type DailyLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date int64 `protobuf:"varint,1,opt,name=Date,proto3" json:"Date,omitempty"` // Date following the epoch format.
	Mood *Mood `protobuf:"bytes,2,opt,name=Mood,proto3" json:"Mood,omitempty"`  // Mood log of the day.
}

func (x *DailyLog) Reset() {
	*x = DailyLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_api_protos_tracker_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DailyLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyLog) ProtoMessage() {}

func (x *DailyLog) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_api_protos_tracker_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyLog.ProtoReflect.Descriptor instead.
func (*DailyLog) Descriptor() ([]byte, []int) {
	return file_cmd_api_protos_tracker_api_proto_rawDescGZIP(), []int{1}
}

func (x *DailyLog) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *DailyLog) GetMood() *Mood {
	if x != nil {
		return x.Mood
	}
	return nil
}

var File_cmd_api_protos_tracker_api_proto protoreflect.FileDescriptor

var file_cmd_api_protos_tracker_api_proto_rawDesc = []byte{
	0x0a, 0x20, 0x63, 0x6d, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x04, 0x4d, 0x6f, 0x6f, 0x64,
	0x12, 0x28, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x6f, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x41, 0x0a, 0x08, 0x44, 0x61,
	0x69, 0x6c, 0x79, 0x4c, 0x6f, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x4d, 0x6f,
	0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x65, 0x72, 0x2e, 0x4d, 0x6f, 0x6f, 0x64, 0x52, 0x04, 0x4d, 0x6f, 0x6f, 0x64, 0x2a, 0x1f, 0x0a,
	0x09, 0x4d, 0x6f, 0x6f, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x61,
	0x70, 0x70, 0x79, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x61, 0x64, 0x10, 0x01, 0x32, 0x44,
	0x0a, 0x0a, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x41, 0x50, 0x49, 0x12, 0x36, 0x0a, 0x09,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x12, 0x11, 0x2e, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x4c, 0x6f, 0x67, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x6e, 0x69, 0x61, 0x63, 0x6c, 0x64, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2d, 0x69, 0x6e, 0x2d, 0x67, 0x6f, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_api_protos_tracker_api_proto_rawDescOnce sync.Once
	file_cmd_api_protos_tracker_api_proto_rawDescData = file_cmd_api_protos_tracker_api_proto_rawDesc
)

func file_cmd_api_protos_tracker_api_proto_rawDescGZIP() []byte {
	file_cmd_api_protos_tracker_api_proto_rawDescOnce.Do(func() {
		file_cmd_api_protos_tracker_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_api_protos_tracker_api_proto_rawDescData)
	})
	return file_cmd_api_protos_tracker_api_proto_rawDescData
}

var file_cmd_api_protos_tracker_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmd_api_protos_tracker_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cmd_api_protos_tracker_api_proto_goTypes = []interface{}{
	(MoodState)(0),        // 0: tracker.MoodState
	(*Mood)(nil),          // 1: tracker.Mood
	(*DailyLog)(nil),      // 2: tracker.DailyLog
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_cmd_api_protos_tracker_api_proto_depIdxs = []int32{
	0, // 0: tracker.Mood.State:type_name -> tracker.MoodState
	1, // 1: tracker.DailyLog.Mood:type_name -> tracker.Mood
	2, // 2: tracker.TrackerAPI.CreateLog:input_type -> tracker.DailyLog
	3, // 3: tracker.TrackerAPI.CreateLog:output_type -> google.protobuf.Empty
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cmd_api_protos_tracker_api_proto_init() }
func file_cmd_api_protos_tracker_api_proto_init() {
	if File_cmd_api_protos_tracker_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_api_protos_tracker_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mood); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_api_protos_tracker_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DailyLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_api_protos_tracker_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_api_protos_tracker_api_proto_goTypes,
		DependencyIndexes: file_cmd_api_protos_tracker_api_proto_depIdxs,
		EnumInfos:         file_cmd_api_protos_tracker_api_proto_enumTypes,
		MessageInfos:      file_cmd_api_protos_tracker_api_proto_msgTypes,
	}.Build()
	File_cmd_api_protos_tracker_api_proto = out.File
	file_cmd_api_protos_tracker_api_proto_rawDesc = nil
	file_cmd_api_protos_tracker_api_proto_goTypes = nil
	file_cmd_api_protos_tracker_api_proto_depIdxs = nil
}
